apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-pr-review-bot-chroma-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3

